help_plus = """
HERE IS HELP FOR BARCODES :-
✣ {VSx01} - SCAMMER.
✣ {VSx02} - SPAM ADDING MEMBER.
✣ {VSx03} - ABUSE SPAM.
✣ {VSx04} - NSFW SPAMMER.
✣ {VSx05} - IMPERSONATION.
✣ {VSx06} - MD/BTC SCAM.
✣ {VSx07} - ADDING SPAMBOTS.
✣ {VSx08} - ILLEGAL.
✣ {VSx09} - PHISHING.
✣ {VSx10} - FRAUD PROMOTION  [ANY KIND].
✣ {VSx11} - CYBER THREATENING / CYBER BULLY.
✣ {VSx12} - CHILD ABUSE.
✣ {VSx13} - BAN EVASION.
✣ {VSx14} - SPAMBOT.
✣ {VSx15} - RAID INITIALIZOR. 
✣ {VSx16} - RAID PARTICIPANT.
✣ {VSx17} - KRIMINALANT.
✣ {VSx18} - RAID/SPAM INFLAMMER.
✣ {VSx19} - RAID // SCAMMER BAN BY SCANNER BOT'S REPORTS
"""

__plugin_name__ = "Bancodes"
