help_plus = """
HERE IS HELP FOR BARCODES :-
❂ {SCx00} ❂- SCAMMER.
❂ {SCx01} ❂- SPAM ADDING MEMBER.
❂ {SCx03} ❂- ABUSE SPAM.
❂ {SCx04} ❂- NSFW SPAMMER.
❂ {SCx06} ❂- IMPERSONATION.
❂ {SCx07} ❂- MD/BTC SCAM.
❂ {SCx08} ❂- ADDING SPAMBOTS.
❂ {SCx10} ❂- ILLEGAL.
❂ {SCx11} ❂- PHISHING.
❂ {SCx12} ❂- FRAUD PROMOTION  [ANY KIND].
❂ {SCx13} ❂- CYBER THREATENING / CYBER BULLY.
❂ {SCx14} ❂- CHILD ABUSE.
❂ {SCx15} ❂- BAN EVASION.
❂ {SCx16} ❂- SPAMBOT.
❂ {SCx17} ❂- RAID INITIALIZOR. 
❂ {SCx18} ❂- RAID PARTICIPANT.
❂ {SCx19} ❂- KRIMINALANT.

❂ {SCx20} ❂- RAID/SPAM INFLAMMER.

❂ {RD-00} ❂- RAID // SCAMMER BAN BY SCANNER BOT'S REPORTS
"""

__plugin_name__ = "Bancodes"
